address = "127.0.0.1"
federates = [
    {
        site_id = 1,
        application_id = 1,
        entity_id = 1,
    },
    {
        site_id = 2,
        application_id =  2,
        entity_id = 2,
    }
]
