[book]
authors = ["Cameron Howell"]
language = "en"
src = "src"

[output.html]
default-theme = "mocha"
preferred-dark-theme = "mocha"
git-repository-url = "https://github.com/crhowell3/centurion"
edit-url-template = "https://github.com/crhowell3/centurion/edit/main/book/{path}"
additional-css = ["./theme/catppuccin.css"]
